remote_theme: joshreedschramm/flexible-jekyll
title: Josh Reed Schramm - A Guy from Ohio
description: >
  Home page for Josh Reed Schramm. VP of Engineering at Groupize, Dad, Developer
  and other fun things. I write about tech, programming, politics and really
  whatever I feel like.
permalink: ':title/'
baseurl: ""
url: "https://www.joshreedschramm.com"

author: Josh Reed Schramm
author-img: josh-schramm.jpg
about-author: VP of Engineering @ Groupize. I'm a dad, developer and help a kick ass team be successful.
social-twitter: JoshReedSchramm
social-facebook: joshreedschramm
social-github: joshreedschramm
social-linkedin: joshschramm
social-email: josh.schramm@gmail.com

# Tracker
analytics: "UA-9223562-1"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
